[toolchain]

# channel = "nightly-2025-02-06"
channel = "nightly-2025-02-06"
components = ["rustfmt", "rustc-dev", "llvm-tools-preview"]
# targets = [ "wasm32-unknown-unknown", "thumbv2-none-eabi" ]
targets = [
  # "x86_64-unknown-linux-gnu",
  # "wasm32-unknown-unknown",
  # "aarch64-unknown-linux-musl",
  # "x86_64-unknown-linux-musl",
  "riscv64gc-unknown-none-elf",
]
profile = "minimal"
